var rule = {
            title: '美柏影视',
            host: 'https://www.mp4br.com',
            url: '/dy/fyclass-fypage.html',
            searchUrl: '/sousuo/page/fypage/wd/**.html',
            searchable: 2,
            quickSearch: 0,
            headers: {
                'User-Agent': 'MOBILE_UA',
            },
            timeout: 5000,
            class_parse: '.g_wrap_p&&li:lt(6);a&&Text;a&&href;.*/(.*?).html',
            play_parse: true,
            lazy: `js:input = {parse: 1, url: input, js: ''}`,
            double: true,
            推荐: '*',
            一级: 'body&&.img-list&&li;a&&title;img&&src;;a&&href',
            二级: {
                title: 'h1&&Text;.info.fn-clear&&dl:eq(7)&&Text',
                img: 'img&&src',
                desc: '.info.fn-clear&&dl:eq(1)&&Text;.info.fn-clear&&dl:eq(6)&&Text;.info.fn-clear&&dl:eq(4)&&Text;.info.fn-clear&&dl&&Text;.info.fn-clear&&dl:eq(2)&&Text',
                content: '.tjuqing&&Text',
                tabs: '.down-title',
                lists: '.video_list:eq(#id)&&a',
            },
            搜索: 'ul.show-list&&li;img&&alt;img&&src;.color&&Text;a&&href',
        }